#!/usr/bin/env bash

function cache_op_session() {
  ACCOUNT="$1"
  NAME="$2"
  TOKEN="$3"

  echo "protocol=https
host=$ACCOUNT
username=$NAME
password=$TOKEN
" | git credential-cache store
}

function get_op_session() {
  ACCOUNT="$1"
  NAME="$2"

  echo "protocol=https
host=$ACCOUNT
username=$NAME
" | git credential-cache get | grep 'password=' | cut -d= -f2
}

function reset_op_session() {
  ACCOUNT="$1"
  NAME="$2"

  echo "protocol=https
host=$ACCOUNT
username=$NAME
" | git credential-cache erase
}

function get_credential() {
  ACCOUNT="$1"
  NAME="$2"

  OP_SESSION="--account=$ACCOUNT --session=$(get_op_session "$ACCOUNT" "$NAME")"

  if ! op list vaults $OP_SESSION >/dev/null 2>&1; then
    TOKEN="$(op signin "$ACCOUNT" --output=raw </dev/tty)"
    cache_op_session "$ACCOUNT" "$NAME" "$TOKEN"
    OP_SESSION="--account=$ACCOUNT --session=$(get_op_session "$ACCOUNT" "$NAME")"
  fi

  CREDENTIAL="$(op get item "$NAME" $OP_SESSION --fields username,password --format CSV)"

  echo username="$(echo "$CREDENTIAL" | cut -d, -f1)"
  echo password="$(echo "$CREDENTIAL" | cut -d, -f2)"
}

case "$3" in

'get')
  get_credential "$1" "$2"
  ;;

'erase')
  reset_op_session "$1" "$2"
  ;;

esac
