#!/usr/bin/env bash

account="$1"
item_name="$2"
git_credential_action="$3"

op_session_path="$HOME"/.opsession/$account
mkdir -p "$HOME"/.opsession
touch "$op_session_path"
chmod 600 "$op_session_path"

op_session_varname=OP_SESSION_$account
export "$op_session_varname"="$(cat "$op_session_path")"

function handle_signin_response() {
  if [[ -z ${!op_session_varname} ]]; then
    exit 1
  fi
}

function auto_signin() {
  if [[ -z ${!op_session_varname} ]]; then
    export "$op_session_varname"="$(op signin --account "$account" --raw </dev/tty | tee "$op_session_path")"
    handle_signin_response
  else
    if ! op list vaults --account="$account" >/dev/null 2>&1; then
      export "$op_session_varname"="$(op signin --account "$account" --raw </dev/tty | tee "$op_session_path")"
      handle_signin_response
    fi
  fi
}

function get_credential() {
  credential="$(op item get "$item_name" --account "$account" --fields label=username,label=password --format json)"

  ssh_user="$(echo "$credential" | jq -r ".[] | select(.id == "'"username"'") | .value")"
  ssh_pass="$(echo "$credential" | jq -r ".[] | select(.id == "'"password"'") | .value")"

  echo username="$ssh_user"
  echo password="$ssh_pass"
}

case "$git_credential_action" in

'get')
  auto_signin
  get_credential
  ;;

esac
